### ISSUE TITLE
Re-enable creation of OMOP connections.

### ISSUE THREAD

**Issue by rkiefer** [PheMA/phema-workbench-app#1]
Allow users to create a new OMOP connection.   
- Verify it appears in the remote connections panel.  
- Verify it appears in the Run connections pull down.
- Verify connections list maintains alphabetical order.
- Verify execution results are displayed correctly.

**Comment by psbrandt** [comment]
OMOP execution should still be mostly working. I made a change with [this commit](https://github.com/PheMA/phema-workbench-app/commit/7dd77079623b8780646c89e4441613d84e4c5455) that broke configuring a new OMOP connection and preparing the API request payload.

Specifically, the API does still support OMOP execution (see [`CohortDefinitionResource`](https://github.com/PheMA/phema-workbench-api/blob/master/src/api/main/org/phema/workbench/api/resources/ohdsi/cohortdefinition/CohortDefinitionResource.java)). For example, posting a [`CohortDefinitionRequest`](https://github.com/PheMA/phema-workbench-api/blob/master/src/api/main/org/phema/workbench/api/resources/ohdsi/cohortdefinition/CohortDefinitionRequest.java) to http://workbench.local.phema.science:4321/api/v1/omop/cohortdefinition should return a JSON representation of the OMOP cohort definition.

The reason I had to make the breaking change is because `cqf-ruler` (and FHIR) requires that a [`Parameters`](https://www.hl7.org/fhir/parameters.html) resource be posted to [extended operations](https://www.hl7.org/fhir/operations.html). Before, when executing CQL using FHIR, I was just posting something like the following, because I wasn't using `cqf-ruler`, which is more FHIR compliant than [`cql_execution_service`](https://github.com/DBCG/cql_execution_service).

```json
{
    "code": "define _: 1 + 1 // cql source code"
}
```
Previously, in the <kbd>Add CQL Connection</kbd> panel, you could pick which JSON property should contain the CQL source code (`code` in the example above). [This](https://github.com/PheMA/phema-workbench-app/commit/7dd77079623b8780646c89e4441613d84e4c5455#diff-74b8e57d3a2606fcf94c68ae1f1c75d4L109-L126) is the change I made to remove that feature, since FHIR requires that the CQL source is in a parameter with `name`=`cql`.

I also had to update the JavaScript to post this instead:

```json
{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "cql",
            "valueString": "define _: 1 + 1 // cql source code"
        }
    ]
}
```

[Here](https://github.com/PheMA/phema-workbench-app/commit/7dd77079623b8780646c89e4441613d84e4c5455#diff-f70afd06107c80add5c1734aebd7de1dR8-R31) is the change I made to support generating the parameters resource (scroll down to the highlighted part).

### Solution

I think the solution is to duplicate the `cql` folder [here](https://github.com/PheMA/phema-workbench-app/tree/master/jsx/components/connections) and call it `omop`, and update the contained components accordingly. You'll also need to add a new case here to show your new component:

https://github.com/PheMA/phema-workbench-app/blob/326c2d736e90df7d3e460a6e4c9b23c6c928f991/jsx/components/connections/Connections.jsx#L146-L152

That file also contains some commented out connections that you could uncomment.

Finally, you'll need to make a change here to prepare the right payload for the OMOP API endpoint. That is, instead of always creating a `Parameters` resource, prepare something that looks like the first JSON snippet above.

https://github.com/PheMA/phema-workbench-app/blob/7dd77079623b8780646c89e4441613d84e4c5455/jsx/components/cql/Window.jsx#L24-L41

### Alternative Solution

Update the [API endpoints](https://github.com/PheMA/phema-workbench-api/blob/feae747dc96f085c87024c86bea9d182aef4474a/src/api/main/org/phema/workbench/api/resources/ohdsi/cohortdefinition/CohortDefinitionResource.java#L19) to accept a `Parameters` resources instead of a `CohortDefinitionRequest`.

**Comment by psbrandt** [comment]
I'll take this over since it's a quick fix while I'm playing around with the connections mechanism.

**Comment by psbrandt** [comment]
Done
